version: '2'

services:
  db:
    image: postgres:latest
    networks:
      - backend
    ports:
      - 5432:5432

  dbaccess:
    image: dbaccess:dev
    networks:
      - backend
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ./dbaccess:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
    depends_on:
      - db

networks:
  backend: